# Generated by Django 6.0.7 on 2026-07-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='physical_symptoms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='predicted_emotion',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
