from recommendations.models import YogaPose

YogaPose.objects.all().delete()

poses = [
# {
# "name":"Child's Pose","sanskrit_name":"Balasana","difficulty":"Beginner","duration":5,
# "description":"A gentle resting pose that relaxes the body and mind.",
# "benefits":"Relieves stress, calms the nervous system, stretches hips, thighs and back, reduces fatigue.",
# "contraindications":"Severe knee injury, late pregnancy unless modified.",
# "instructions":"Kneel, sit on heels, fold forward, stretch arms, rest forehead on the mat and breathe slowly.",
# "target_emotions":"Stress,Anxiety,Depression",
# "target_symptoms":"Fatigue,Back Pain,Tension",
# "avoid_conditions":"Severe Knee Injury",
# "difficulty_score":1},
{
"name":"Cat-Cow Pose","sanskrit_name":"Marjaryasana-Bitilasana","difficulty":"Beginner","duration":5,
"description":"Gentle spinal mobility sequence.",
"benefits":"Improves spinal flexibility, reduces stiffness, eases back pain.",
"contraindications":"Recent wrist injury.",
"instructions":"On hands and knees alternate arching and rounding the spine with the breath.",
"target_emotions":"Stress,Anxiety",
"target_symptoms":"Back Pain,Neck Stiffness",
"avoid_conditions":"Severe Wrist Injury",
"difficulty_score":1},
{
"name":"Cobra Pose","sanskrit_name":"Bhujangasana","difficulty":"Beginner","duration":3,
"description":"Backbend opening the chest.",
"benefits":"Strengthens spine, opens chest, improves posture.",
"contraindications":"Pregnancy, recent abdominal surgery.",
"instructions":"Lie prone, place palms near chest, lift chest gently.",
"target_emotions":"Depression,Stress",
"target_symptoms":"Back Pain,Poor Posture",
"avoid_conditions":"Pregnancy,Recent Abdominal Surgery",
"difficulty_score":2},
{
"name":"Mountain Pose","sanskrit_name":"Tadasana","difficulty":"Beginner","duration":3,
"description":"Foundational standing pose.",
"benefits":"Improves posture, balance and awareness.",
"contraindications":"",
"instructions":"Stand tall with feet together and breathe evenly.",
"target_emotions":"Normal,Stress",
"target_symptoms":"Poor Posture",
"avoid_conditions":"",
"difficulty_score":1},
{
"name":"Tree Pose","sanskrit_name":"Vrikshasana","difficulty":"Beginner","duration":3,
"description":"Single-leg balancing pose.",
"benefits":"Improves focus, balance and confidence.",
"contraindications":"Serious balance disorders.",
"instructions":"Stand on one leg and place other foot on inner thigh.",
"target_emotions":"Anxiety,Stress",
"target_symptoms":"Poor Balance",
"avoid_conditions":"Vertigo",
"difficulty_score":2},
{
"name":"Bridge Pose","sanskrit_name":"Setu Bandhasana","difficulty":"Beginner","duration":4,
"description":"Gentle backbend.",
"benefits":"Strengthens back and glutes, opens chest.",
"contraindications":"Neck injury.",
"instructions":"Lie on back, bend knees, lift hips upward.",
"target_emotions":"Depression,Stress",
"target_symptoms":"Back Pain,Fatigue",
"avoid_conditions":"Neck Injury",
"difficulty_score":2},
{
"name":"Legs Up the Wall","sanskrit_name":"Viparita Karani","difficulty":"Beginner","duration":8,
"description":"Restorative inversion.",
"benefits":"Reduces stress, swelling and fatigue.",
"contraindications":"Glaucoma.",
"instructions":"Lie on back with legs resting vertically on a wall.",
"target_emotions":"Stress,Anxiety,Bi-Polar",
"target_symptoms":"Fatigue,Swollen Legs",
"avoid_conditions":"Glaucoma",
"difficulty_score":1},
{
"name":"Easy Pose","sanskrit_name":"Sukhasana","difficulty":"Beginner","duration":10,
"description":"Comfortable seated meditation pose.",
"benefits":"Promotes calmness and mindful breathing.",
"contraindications":"",
"instructions":"Sit cross-legged with upright spine and relaxed shoulders.",
"target_emotions":"Anxiety,Stress,Personality Disorder",
"target_symptoms":"Mental Restlessness",
"avoid_conditions":"",
"difficulty_score":1},
{
"name":"Corpse Pose","sanskrit_name":"Savasana","difficulty":"Beginner","duration":10,
"description":"Deep relaxation pose.",
"benefits":"Relaxes body and mind, lowers stress.",
"contraindications":"",
"instructions":"Lie flat, relax every muscle and breathe naturally.",
"target_emotions":"Stress,Anxiety,Depression,Suicidal,Bi-Polar",
"target_symptoms":"Fatigue,Insomnia",
"avoid_conditions":"",
"difficulty_score":1},
{
"name":"Seated Forward Bend","sanskrit_name":"Paschimottanasana","difficulty":"Intermediate","duration":5,
"description":"Forward fold stretch.",
"benefits":"Calms mind, stretches hamstrings and spine.",
"contraindications":"Herniated disc.",
"instructions":"Sit with legs extended and fold forward from hips.",
"target_emotions":"Stress,Depression",
"target_symptoms":"Back Tightness",
"avoid_conditions":"Herniated Disc",
"difficulty_score":2},
{
"name":"Downward Facing Dog","sanskrit_name":"Adho Mukha Svanasana","difficulty":"Intermediate","duration":5,
"description":"Full body stretch.",
"benefits":"Strengthens arms and stretches spine.",
"contraindications":"Wrist injury.",
"instructions":"Lift hips forming an inverted V shape.",
"target_emotions":"Stress,Normal",
"target_symptoms":"Back Pain,Tight Hamstrings",
"avoid_conditions":"Severe Wrist Injury",
"difficulty_score":2},
{
"name":"Camel Pose","sanskrit_name":"Ustrasana","difficulty":"Intermediate","duration":3,
"description":"Deep chest opener.",
"benefits":"Improves posture and energy.",
"contraindications":"Neck injury.",
"instructions":"Kneel and reach hands to heels while opening chest.",
"target_emotions":"Depression",
"target_symptoms":"Poor Posture",
"avoid_conditions":"Neck Injury",
"difficulty_score":3},
{
"name":"Triangle Pose","sanskrit_name":"Trikonasana","difficulty":"Beginner","duration":3,
"description":"Standing side stretch.",
"benefits":"Improves flexibility and balance.",
"contraindications":"Low blood pressure.",
"instructions":"Spread legs, extend one arm down to shin and other upward.",
"target_emotions":"Normal,Stress",
"target_symptoms":"Hip Tightness",
"avoid_conditions":"Low Blood Pressure",
"difficulty_score":2},
{
"name":"Warrior I","sanskrit_name":"Virabhadrasana I","difficulty":"Beginner","duration":3,
"description":"Standing strength pose.",
"benefits":"Builds confidence and leg strength.",
"contraindications":"Hip injury.",
"instructions":"Lunge forward with arms overhead.",
"target_emotions":"Depression,Normal",
"target_symptoms":"Weak Legs",
"avoid_conditions":"Hip Injury",
"difficulty_score":2},
{
"name":"Warrior II","sanskrit_name":"Virabhadrasana II","difficulty":"Beginner","duration":3,
"description":"Strong standing pose.",
"benefits":"Improves stamina and focus.",
"contraindications":"Hip injury.",
"instructions":"Open hips and extend arms parallel to floor.",
"target_emotions":"Stress,Normal",
"target_symptoms":"Weak Legs",
"avoid_conditions":"Hip Injury",
"difficulty_score":2},
{
"name":"Extended Puppy Pose","sanskrit_name":"Uttana Shishosana","difficulty":"Beginner","duration":4,
"description":"Gentle shoulder opener.",
"benefits":"Relieves tension in shoulders and spine.",
"contraindications":"Shoulder injury.",
"instructions":"Walk hands forward from tabletop while lowering chest.",
"target_emotions":"Stress,Anxiety",
"target_symptoms":"Shoulder Tightness",
"avoid_conditions":"Shoulder Injury",
"difficulty_score":1},
{
"name":"Happy Baby Pose","sanskrit_name":"Ananda Balasana","difficulty":"Beginner","duration":4,
"description":"Hip opening pose.",
"benefits":"Releases lower back and hips.",
"contraindications":"Knee injury.",
"instructions":"Lie on back holding feet with knees bent.",
"target_emotions":"Stress,Anxiety",
"target_symptoms":"Back Pain,Hip Tightness",
"avoid_conditions":"Severe Knee Injury",
"difficulty_score":1},
{
"name":"Butterfly Pose","sanskrit_name":"Baddha Konasana","difficulty":"Beginner","duration":5,
"description":"Seated hip opener.",
"benefits":"Improves hip flexibility and relaxation.",
"contraindications":"Groin injury.",
"instructions":"Sit with soles together and gently press knees downward.",
"target_emotions":"Stress,Normal",
"target_symptoms":"Hip Tightness",
"avoid_conditions":"Groin Injury",
"difficulty_score":1},
{
"name":"Half Lord of the Fishes","sanskrit_name":"Ardha Matsyendrasana","difficulty":"Intermediate","duration":4,
"description":"Seated spinal twist.",
"benefits":"Improves spinal mobility.",
"contraindications":"Pregnancy.",
"instructions":"Twist torso while seated with bent knees.",
"target_emotions":"Stress",
"target_symptoms":"Back Stiffness",
"avoid_conditions":"Pregnancy",
"difficulty_score":2},
{
"name":"Plank Pose","sanskrit_name":"Phalakasana","difficulty":"Intermediate","duration":2,
"description":"Core strengthening pose.",
"benefits":"Strengthens entire body.",
"contraindications":"Shoulder injury.",
"instructions":"Hold body in straight line supported by hands and toes.",
"target_emotions":"Normal",
"target_symptoms":"Weak Core",
"avoid_conditions":"Shoulder Injury",
"difficulty_score":3},
{
"name":"Boat Pose","sanskrit_name":"Navasana","difficulty":"Intermediate","duration":2,
"description":"Core balance pose.",
"benefits":"Builds abdominal strength and focus.",
"contraindications":"Lower back injury.",
"instructions":"Balance on sitting bones with lifted legs.",
"target_emotions":"Normal,Depression",
"target_symptoms":"Weak Core",
"avoid_conditions":"Lower Back Injury",
"difficulty_score":3},
{
"name":"Eagle Pose","sanskrit_name":"Garudasana","difficulty":"Intermediate","duration":3,
"description":"Balancing twist pose.",
"benefits":"Improves concentration and balance.",
"contraindications":"Knee injury.",
"instructions":"Wrap arms and legs while balancing.",
"target_emotions":"Anxiety,Personality Disorder",
"target_symptoms":"Poor Balance",
"avoid_conditions":"Knee Injury",
"difficulty_score":3},
{
"name":"Lotus Pose","sanskrit_name":"Padmasana","difficulty":"Advanced","duration":10,
"description":"Meditation posture.",
"benefits":"Encourages deep meditation and calmness.",
"contraindications":"Knee injury.",
"instructions":"Cross legs deeply placing feet on opposite thighs.",
"target_emotions":"Stress,Anxiety,Bi-Polar",
"target_symptoms":"Mental Restlessness",
"avoid_conditions":"Knee Injury",
"difficulty_score":4},
{
"name":"Reclining Bound Angle","sanskrit_name":"Supta Baddha Konasana","difficulty":"Beginner","duration":8,
"description":"Restorative reclining pose.",
"benefits":"Promotes relaxation and deep breathing.",
"contraindications":"Hip injury.",
"instructions":"Lie back with soles together and knees apart.",
"target_emotions":"Suicidal,Depression,Stress",
"target_symptoms":"Fatigue,Mental Restlessness",
"avoid_conditions":"Hip Injury",
"difficulty_score":1},
{
"name":"Standing Forward Fold","sanskrit_name":"Uttanasana","difficulty":"Beginner","duration":4,
"description":"Forward standing stretch.",
"benefits":"Calms mind and stretches entire back body.",
"contraindications":"Severe back injury.",
"instructions":"Fold forward from hips allowing head to relax.",
"target_emotions":"Stress,Anxiety",
"target_symptoms":"Back Tightness,Fatigue",
"avoid_conditions":"Severe Back Injury",
"difficulty_score":1},
{
"name":"Pigeon Pose","sanskrit_name":"Eka Pada Rajakapotasana","difficulty":"Intermediate","duration":4,
"description":"Deep hip-opening pose that releases tension.",
"benefits":"Improves hip flexibility, relieves lower back discomfort and reduces stiffness.",
"contraindications":"Recent hip or knee injury.",
"instructions":"Bring one knee forward, extend the opposite leg back and fold gently over the front leg.",
"target_emotions":"Stress,Depression",
"target_symptoms":"Hip Tightness,Back Tightness",
"avoid_conditions":"Hip Injury,Knee Injury",
"difficulty_score":3},

{
"name":"Low Lunge","sanskrit_name":"Anjaneyasana","difficulty":"Beginner","duration":3,
"description":"Gentle lunge that stretches the hips and thighs.",
"benefits":"Improves hip mobility, strengthens legs and enhances posture.",
"contraindications":"Severe knee injury.",
"instructions":"Step one foot forward, lower the back knee and raise both arms overhead.",
"target_emotions":"Normal,Stress",
"target_symptoms":"Hip Tightness,Weak Legs",
"avoid_conditions":"Severe Knee Injury",
"difficulty_score":2},

{
"name":"Puppy Stretch","sanskrit_name":"Uttana Shishosana","difficulty":"Beginner","duration":4,
"description":"Relaxing shoulder and upper back stretch.",
"benefits":"Relieves shoulder tension and improves spinal flexibility.",
"contraindications":"Shoulder injury.",
"instructions":"From tabletop, walk your hands forward and lower your chest toward the floor.",
"target_emotions":"Stress,Anxiety",
"target_symptoms":"Shoulder Tightness,Back Stiffness",
"avoid_conditions":"Shoulder Injury",
"difficulty_score":1},

{
"name":"Fish Pose","sanskrit_name":"Matsyasana","difficulty":"Intermediate","duration":3,
"description":"Chest-opening backbend that improves breathing.",
"benefits":"Opens the chest, improves posture and relieves neck stiffness.",
"contraindications":"Neck injury or severe back injury.",
"instructions":"Lie on your back, lift your chest and gently rest the crown of your head on the mat.",
"target_emotions":"Depression,Stress",
"target_symptoms":"Poor Posture,Neck Stiffness",
"avoid_conditions":"Neck Injury",
"difficulty_score":3},

{
"name":"Garland Pose","sanskrit_name":"Malasana","difficulty":"Beginner","duration":4,
"description":"Deep yogic squat improving lower body mobility.",
"benefits":"Opens hips, stretches ankles and strengthens legs.",
"contraindications":"Knee injury.",
"instructions":"Squat with feet apart, bring palms together and keep the spine upright.",
"target_emotions":"Normal,Stress",
"target_symptoms":"Hip Tightness,Weak Legs",
"avoid_conditions":"Knee Injury",
"difficulty_score":2},

{
"name":"Wide-Legged Forward Fold","sanskrit_name":"Prasarita Padottanasana","difficulty":"Intermediate","duration":4,
"description":"Standing forward bend with a wide stance.",
"benefits":"Stretches hamstrings, spine and improves circulation.",
"contraindications":"Severe lower back injury.",
"instructions":"Stand with legs wide apart and fold forward from the hips.",
"target_emotions":"Stress,Anxiety",
"target_symptoms":"Back Tightness,Tight Hamstrings",
"avoid_conditions":"Severe Back Injury",
"difficulty_score":2},

{
"name":"Reverse Warrior","sanskrit_name":"Viparita Virabhadrasana","difficulty":"Intermediate","duration":3,
"description":"Standing side bend improving strength and flexibility.",
"benefits":"Strengthens legs, stretches the side body and improves endurance.",
"contraindications":"Hip injury.",
"instructions":"From Warrior II, reach the front arm overhead while sliding the back hand down the leg.",
"target_emotions":"Normal,Depression",
"target_symptoms":"Weak Legs,Poor Posture",
"avoid_conditions":"Hip Injury",
"difficulty_score":3},

{
"name":"Dolphin Pose","sanskrit_name":"Ardha Pincha Mayurasana","difficulty":"Intermediate","duration":3,
"description":"Forearm inversion strengthening shoulders and core.",
"benefits":"Builds shoulder strength and stretches the spine.",
"contraindications":"Shoulder injury or glaucoma.",
"instructions":"Place forearms on the floor and lift hips into an inverted V shape.",
"target_emotions":"Normal,Stress",
"target_symptoms":"Shoulder Tightness,Weak Core",
"avoid_conditions":"Shoulder Injury,Glaucoma",
"difficulty_score":3},

{
"name":"Standing Side Bend","sanskrit_name":"Ardha Chandrasana Side Stretch","difficulty":"Beginner","duration":2,
"description":"Simple standing stretch for the sides of the body.",
"benefits":"Improves flexibility, posture and relieves muscle tension.",
"contraindications":"Recent rib injury.",
"instructions":"Stand tall, raise both arms overhead and lean gently to each side.",
"target_emotions":"Stress,Anxiety",
"target_symptoms":"Tension,Poor Posture",
"avoid_conditions":"Rib Injury",
"difficulty_score":1},

{
"name":"Supine Spinal Twist","sanskrit_name":"Supta Matsyendrasana","difficulty":"Beginner","duration":5,
"description":"Gentle reclining spinal twist promoting relaxation.",
"benefits":"Relieves back stiffness, improves spinal mobility and calms the nervous system.",
"contraindications":"Recent spinal surgery.",
"instructions":"Lie on your back, bend one knee across the body while keeping shoulders on the floor.",
"target_emotions":"Stress,Anxiety,Depression",
"target_symptoms":"Back Stiffness,Insomnia",
"avoid_conditions":"Recent Spinal Surgery",
"difficulty_score":1},
]

for p in poses:
    YogaPose.objects.create(**p)

print(f"Successfully imported {YogaPose.objects.count()} yoga poses.")
