# Generated by Django 6.0.7 on 2026-07-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YogaPose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sanskrit_name', models.CharField(blank=True, max_length=100)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('description', models.TextField()),
                ('benefits', models.TextField(help_text='Separate benefits using commas')),
                ('contraindications', models.TextField(blank=True, help_text='Separate contraindications using commas')),
                ('instructions', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='yoga/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
