# Generated by Django 6.0.7 on 2026-07-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogapose',
            name='avoid_conditions',
            field=models.CharField(blank=True, help_text='Pregnancy,Knee Injury,etc', max_length=300),
        ),
        migrations.AddField(
            model_name='yogapose',
            name='difficulty_score',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='yogapose',
            name='target_emotions',
            field=models.CharField(default='', help_text='Comma separated emotions', max_length=300),
        ),
        migrations.AddField(
            model_name='yogapose',
            name='target_symptoms',
            field=models.CharField(default='', help_text='Comma separated symptoms', max_length=300),
        ),
        migrations.AlterField(
            model_name='yogapose',
            name='benefits',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='yogapose',
            name='contraindications',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='yogapose',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
    ]
